### ISSUE TITLE
Exception: System.ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported

### ISSUE THREAD

**Issue by ivastokic** [Flagsmith/flagsmith-dotnet-client#88] opened 2024-01-24 13:42 UTC
Hi,
We were getting this error in production environment on one of our pods:

![Screenshot 2024-01-24 at 14 26 26](https://github.com/Flagsmith/flagsmith-dotnet-client/assets/112628083/b55db674-4d14-4aea-b762-e933179efbfb)

It started yesterday evening, and restarting of the pod stopped it. We followed your example how to register service, also didn't have any related changes recently. Stack pointing to this one:

```
public async Task TrackFeature(string featureName)
    {
      int num;
      this.AnalyticsData[featureName] = this.AnalyticsData.TryGetValue(featureName, out num) ? num + 1 : 1;
      if ((DateTime.Now - this._LastFlushed).Seconds <= this._FlushIntervalSeconds)
        return;
      await this.Flush();
    } 
```
 Do you have any idea why this happened, could it be related to lack of thread safety?

We are using version 5.0.1

**Comment by novakzaballa** [comment] 2024-01-24 21:33
Hi @ivastokic. Could you please provide us with more information? For example:
Are you using .Net Core or .Net Framework? Which version?
Also, from the info and context provided, it looks like a safe thread issue, however, it is hard to say the root cause or recommend a solution without more context. Can you generate a minimal project reproducing the issue and your current configuration?

**Comment by MaximTkachenko** [comment] 2024-01-28 17:57
It looks like you have a thread sefety issue inside `AnalyticsProcessor`:
- according to ypur documentatyion `FlagsmithClient` is used as a sigletone
- it means that `AnalyticsProcessor` created inside `FlagsmithClient` is used as a sigleton too
- inside `AnalyticsProcessor` you use plain dictionary for feature tracking without any synchronization and periodically you call `Clear` for this dictionary

So you read and modify this dictionary concurrently without any protection. I suggest you to use [ReaderWriterLock ](https://learn.microsoft.com/en-us/dotnet/api/system.threading.readerwriterlock?view=net-8.0) or [CoincurrentDictionary](https://learn.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2?view=net-8.0).
![image](https://github.com/Flagsmith/flagsmith-dotnet-client/assets/1560515/ccdb3877-6b76-4aba-b1c9-07c990822d14)

**Comment by novakzaballa** [comment] 2024-02-20 12:38
Thank you @MaximTkachenko  and sorry about the late reply! We will take a look into this issue soon.
In the mean time if you prefer you can submit a PR and We'll get that merged for you ASAP.

**Comment by novakzaballa** [comment] 2024-03-30 03:27
While I was not able to reproduce the issue with functional tests, or automatic tests using the SDK main functions, I was able to systematically replicate the issue accessing directly the `TrackFeature` method of the `AnalycticsProcessor` class and I put a fix in place in the above PR, which is ready for review now. I will update this thread as soon as we have the fix merged.

**Closed** 2024-04-19 13:25 UTC

**Comment by matthewelwell** [comment] 2024-11-18 15:21
@ivastokic please can you provide more information here? Please provide the stack trace in text form and, ideally, the code on your side which results in the exception. Thanks!
