### ISSUE TITLE
Indefinite hang in MVC view, only where EnableAnalytics is set to true

### ISSUE THREAD

**Issue by DavidPerish** [Flagsmith/flagsmith-dotnet-client#106] opened 2024-07-15 17:29 UTC
Similar to issue #105, we're seeing that requests hang indefinitely. 

Specifically, this is happening in MVC Razor Views (4.8) where EnableAnalytics is set to true.  

When setting EnableAnalytics to false, we do not see the problem.  Also, we did not seem to notice any issue with EnableAnalytics, when flags are accessed from MVC Controller methods.

**Comment by novakzaballa** [comment] 2024-07-15 19:55
In some way, this issue is a duplicate of the [this](https://github.com/Flagsmith/flagsmith-dotnet-client/issues/105). We already have a solution under review in this [PR](https://github.com/Flagsmith/flagsmith-dotnet-client/pull/107).

**Closed by novakzaballa** 2024-07-15 19:55 UTC
